apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://aws.github.io/eks-charts
      targetRevision: 1.11.0 # Specify the version you want to use
      chart: aws-load-balancer-controller
      helm:
        valueFiles:
          - $values/dev/infra/aws-load-balancer-controller/value.yaml
    - repoURL: git@github.com:devopsqba/katana-helm-resources.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # Deploying the AWS LB Controller in kube-system is common
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true
