apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx-charts
      targetRevision: 4.1.2 # You can specify a different version
      chart: ingress-nginx
      helm:
        valueFiles:
          - $values/dev/infra/ingress-nginx/value.yaml
    - repoURL: git@github.com:devopsqba/katana-helm-resources.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx # Specify the namespace where NGINX Ingress will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true
